version: "3.9"
services:
  app:
    build: .
    ports:
      - "3002:3002"
    depends_on:
      - db
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: "mydatabase"
      MYSQL_ROOT_PASSWORD: "mypassword"
    ports:
      - "3306:3306"